<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'uswusc5_pr750');
define('_DB_USER_', 'uswusc5_pr750');
define('_DB_PASSWD_', 'E(46Pc(Sf7');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheFs');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'e1cjth4us8b7dcorown8copv4rlb21vgal1ddycuqofqftvd8ilmq6u7');
define('_COOKIE_IV_', '54laikxc');
define('_PS_CREATION_DATE_', '2014-12-03');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', '8j4PIBaKRYNq19xtX0oX1ZLXMAHgFrTL');
define('_RIJNDAEL_IV_', '8oiHFpDEEsTRT+gEPJAPiA==');
